# - Try to find OpenGLES
# Once done this will define
#  
#  OPENGLES_FOUND        - system has OpenGLES
#  OPENGLES_INCLUDE_DIR  - the GL include directory
#  OPENGLES_LIBRARIES    - Link these to use OpenGLES

FIND_PATH(
	OPENGLES_INCLUDE_DIR GLES/gl.h 
)

FIND_LIBRARY(
	OPENGLES_LIBRARIES NAMES  GLESv1_CM
)

IF(${CORE_SYSTEM_NAME} STREQUAL "ios")
  FIND_LIBRARY(OPENGLES_LIBRARIES NAMES OpenGLES PATHS ${CMAKE_OSX_SYSROOT}/System/Library PATH_SUFFIXES Frameworks NO_DEFAULT_PATH)
  SET(OPENGLES_INCLUDE_DIR ${OPENGLES_LIBRARIES}/Headers)
ENDIF()

IF(OPENGLES_LIBRARIES)
  SET(OPENGLES_FOUND "YES" )
ENDIF(OPENGLES_LIBRARIES)

MARK_AS_ADVANCED(
  OPENGLES_INCLUDE_DIR
  OPENGLES_LIBRARIES
)


